apiVersion: v2
name: vsphere-csi-driver
# upstream version
appVersion: APP_VERSION_PLACEHOLDER
# giantswarm app version
version: CHART_VERSION_PLACEHOLDER
description: A Helm chart for vSphere CSI (Container Storage Interface) Driver
home: https://github.com/giantswarm/vsphere-csi-driver-app
keywords:
  - vsphere
  - vmware
  - csi
icon: https://s.giantswarm.io/app-icons/vsphere/2/icon-light.png
sources:
  - https://github.com/kubernetes-sigs/vsphere-csi-driver
annotations:
  application.giantswarm.io/team: "rocket"
  io.giantswarm.application.upstream-chart-url: "https://github.com/kubernetes-sigs/vsphere-csi-driver"
  io.giantswarm.application.upstream-chart-version: "APP_VERSION_PLACEHOLDER"
